name: flutter_volume_controller
description: A Flutter plugin to control system volume.
version: 1.0.0
homepage: https://github.com/yosemiteyss/flutter_volume_control

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: com.yosemiteyss.flutter_volume_controller
        pluginClass: FlutterVolumeControllerPlugin
      ios:
        pluginClass: FlutterVolumeControllerPlugin
