on:
  push:
    branches:
      - main
      - 'releases/**'
  pull_request:
    branches:
      - main
      - 'releases/**'

jobs:
  build_example_android:
    runs-on: [ self-hosted, linux ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.3.2'
      - run: cd ./example
      - run: flutter pub get
      - run: flutter build apk
      - run: echo "build success!"